language: node_js
node_js:
  - 12
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run build
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_KEY
  file:
    - build/ecs-env-linux
    - build/ecs-env-macos
    - build/ecs-env-win.exe
